- public/members.json
- src/App.js
- src/adminContainers/MemberDetail.js
- src/adminContainers/MembersAdmin.js
- src/adminContainers/PlaceAdd.js
- src/adminContainers/PlaceDetail.js
- src/adminContainers/PlaceEdit.js
- src/adminContainers/PlacesAdmin.js
- src/api/DataApi.js
- src/components/NavBarAdmin.js
- src/css/default.css
- src/css/restaurantCreate.css
- <Admin> - 회원관리 - 회원 목록을 axios를 사용하여 가져오기 구현
- <Admin> - 음식점 관리 - 음식점 상세페이지, 음식점 수정페이지 구현 완료
- <Admin> - 회원 관리 - 백엔드 서버에서 회원 목록 가져와서 화면에 표현 완료.
- <Admin> - 회원관리 - 목록에서 Row클릭시 해당 정보와 관련된 상세 페이지로 전환 구현 완료.
- <Admin> - 회원관리 - 상세정보 페이지에서 권한 부여, 제거 기능을 백엔드 서버로 Request하여 DB까지
- <Admin> - 회원관리 - 상세정보 페이지FindById을 별도의 CustomHook으로 분리하여 재사용성을 높임
- <Admin> - 회원관리 - 상세정보 페이지에서 권한 부여, 제거 후 모달창 닫히면 화면다시 그리기 구현
- <Admin> - 회원관리 - 음식점 목록 페이지 - 데이터 로드 기능 구현 완료
- <Admin> - 음식점 관리 - 음식점 상세페이지 메뉴 사진 불러오기 완료
- <Admin> - 음식점 관리 - 음식점 상세페이지 image url 변경
> 관리자 - 회원 관리 기능 구현 관리자 - 회원 관리 기능 구현 및 음식점 상세페이지(관리자) , 수정 페이지 생성 

- src/containers/SignUp.js
회원가입 구현
- 이메일 중복확인 버튼 제거 -> 자체적인 이메일 중복에 대한 예외처리
- 필드값 미입력시 예외처리
- 비밀번호, 비밀번호 확인 불 일치 시 예외처리
- 비밀번호 패턴에 대한 예외처리
- 휴대폰번호 패턴에 대한 예외처리
https://github.com/user-attachments/assets/719b09cd-33c0-4b01-914f-859191d7f7bf
> [#25] 회원가입 구현

- src/App.js
- src/adminContainers/MemberDetail.js
- src/adminContainers/MembersAdmin.js
- src/adminContainers/PlaceAdd.js
- src/adminContainers/PlaceDetail.js
- src/adminContainers/PlaceEdit.js
- src/adminContainers/PlacesAdmin.js
- src/api/DataApi.js
- src/css/memberDetail.css
- 회원 목록 페이지 > 페이징 처리 완료
- 음식점 목록 페이지 > 페이징 처리 완료
- 음식점 상세 페이지 > 수정 기능 완료 
- 수정페이지 > 기존 이미지와 새로 이미지를 추가하는 부분을 분기하여 처리
> [#21] <ADMIN> - 회원 관리 , 음식점 관리 페이지 기능 수정

- package-lock.json
- package.json
- src/containers/RestaurantList.js
- src/index.js
-  사용자화면 음식점 찾기 페이지 data 연결
- 인피니티 스크롤 기능 추가
- 일정 스크롤 내릴시 10개의 페이지 추가
- 데이터 많을때 테스트 필요(코드 수정될수 있음)
- 인피니티 스크롤 관련 라이브러리 추가
> 사용자화면 음식점 찾기 페이지 data 연결

- src/containers/RestaurantList.js
-  음식점 전체리스트 중복 데이터 처리
-   back에서 리스트화 시킨 음식점 사진 배열로 출력
close [#30 ]
> [사용자] 음식점 전체리스트 중복 데이터 처리

- src/adminContainers/MemberDetail.js
- src/adminContainers/MembersAdmin.js
- src/adminContainers/PlacesAdmin.js
- src/api/DataApi.js
- src/css/restaurantManagement.css
- 회원 목록 페이지 : 검색기능 추가
- 회원 상세 페이지 : 권한 부여시 기존 사용자의 권한 정보에 따라 제거 또는 부여할 권한 선택지 변경
- 음식점 목록 페이지 : 검색기능 추가
> [#29] 회원, 음식점 목록 페이지 검색기능 추가 및 회원 권한 부여 기능 수정

- src/adminContainers/InquiriesAdmin.js
- src/adminContainers/InquiriesDetailAdmin.js
- src/adminContainers/ReservationAdmin.js
- src/adminContainers/ReviewsAdmin.js
- src/css/InquiriesDetailAdmin.css
- src/css/managerInquiryList.css
- src/css/reservationManagement.css
> [관리자] 문의사항, 예약 페이징

- src/containers/Main.js
- src/containers/MonthBest.js
- src/containers/TopReservation.js
-  [사용자] 예약 Top, 이달의 맛집 데이터 구현 
- 예약Top 화면 데이터 화면단 출력
-  이달의 맛집 화면 데이터 화면단에 출력
-  사용자 메인화면 데이터 출력
> [사용자] 예약 Top, 이달의 맛집 데이터 구현 

- src/adminContainers/ReviewsAdmin.js
- src/css/reviewsAdmin.css
- 전체 리뷰 목록 페이지 : 정렬 기능, 검색 기능 추가
- 삭제 버튼 클릭시 리뷰 상세정보 출력 이벤트가 동작 되던거 수정완료.
> [#35] [관리자] 리뷰 관리 - 리뷰 전체 목록 페이지

- src/adminContainers/PlaceAdd.js
- 음식점 등록 페이지 : 음식점 등록시 사장님 이메일에 입력된 id의 권한 검사 후 성공하면 저장 실패하면 화면 하단에 에러메세지 노출.
> [#38] [관리자] 음식점 관리 - 음식점 등록페이지 사장님 아이디에 권한이 없을 경우 하단에 에러메세지 리턴

- src/adminContainers/InquiriesAdmin.js
- src/adminContainers/InquiriesDetailAdmin.js
- src/adminContainers/PlacesAdmin.js
- src/css/InquiriesDetailAdmin.css
- 문의사항 목록페이지 : 검색 기능 구현
- 문의사항 상세페이지 : 돌아가기 버튼 구현
> [#40] [관리자] 문의사항 관리 - 검색기능

- src/adminContainers/ReservationAdmin.js
- src/css/myPageInquiryHistory.css
- src/css/reservationManagement.css
> [#43]관리자 예약페이지 상태값으로 정렬 및 검색기능, css수정

- src/adminContainers/MainAdmin.js
- src/adminContainers/ReviewsAdmin.js
> [#42] [관리자] 메인페이지 - 대시보드 및 주요통계 데이터 DB에서 게더링

- src/App.js
- src/containers/Detail.js
- src/containers/Main.js
- src/containers/MonthBest.js
- src/containers/RestaurantList.js
- src/containers/TopReservation.js
- src/css/detail.css
-  [사용자] 음식점 디테일 페이지 구현
-  음식점 디테일 페이지 구현
-  음식점 이미지 슬라이드 추가
-  음식점 메뉴,리뷰 더보기 기능 및 접기 기능 추가
-  메인,top,이달의 맛집 에서 디테일 화면으로 가는 링크 추가
> [사용자] 음식점 디테일 페이지 구현(예약기능 미구현)

- src/App.js
- src/adminContainers/PlaceEdit.js
- src/adminContainers/ReviewsAdmin.js
- src/containers/MypageBookmark.js
- src/containers/ReservationList.js
- src/context/AuthContext.js
- src/css/myPageBookmark.css
- src/css/myPageReservationList.css
> [사용자] 마이페이지 - 예약 내역, 즐겨찾기 기능 구현

- src/App.js
- src/components/NavBar.js
- src/containers/Detail.js
- src/containers/Main.js
- src/containers/MonthBest.js
- src/containers/RestaurantList.js
- src/containers/TopReservation.js
- src/css/home.css
-  [사용자] 음식점 검색 기능 구현
-  Navbar 검색탭에서 음식점 이름, 주소, 메뉴명 검색시 전체음식점 창에서 음식점 리스트 구현
- 검색시 전체리스트창 새로고침, 엔터키 이벤트추가
- 디테일 값 주소변경
- 메인페이지 더보기 버튼 태그 변경및  css 추가
> [사용자] 음식점 검색 기능 구현

- src/App.js
> [#58] 사용자 음식점 화면 중복 제거

- src/containers/TopReservation.js
- src/css/reservationTop10.css
-  [사용자] 예약 Top 카테고리 기능 구현
-  카테고리 필터 기능 추가
-  카테고리 버튼 css 추가
> [사용자] 예약 Top 카테고리 기능 구현

- src/App.js
- src/containers/InquiryDetail.js
- src/containers/MypageInquiry.js
- src/containers/MypageReviewEdit.js
- src/containers/MypageReviewlist.js
- src/css/inquiry.css
- src/css/myPageInquiryHistory.css
- src/css/myReview.css
- 리뷰 : 로그인된 사용자의 리뷰 불러오기 및 수정,삭제 기능
- 문의사항 : 로그인된 사용자의 리뷰 불러오기 및 수정 기능
> 마이페이지 리뷰, 문의사항 기능

- src/components/Header.js
- src/components/MypageSidebar.js
- src/containers/Mypage.js
- src/containers/SignIn.js
- src/context/AuthContext.js
- src/context/AxiosInstance.js
- src/css/SignIn.css
- src/css/default.css
토큰 사용에 대한 네이밍, 로직이 전반적으로 수정되었습니다.
OAuth 사용자에 대한 로직 모두 작성되었으며 이상있을 시 바로 개선하도록 하겠습니다.
변경사항 중점적으로 확인해야 할 부분
- SignIn.js -> 일반사용자, OAuth 사용자 전반적인 로직 작성
- AuthContext.js -> Token에서 accessToken, refreshToken으로 구분, 재발급 로직
- AxiosInstance.js -> axios 사용 시 토큰재발급에 대한 전역설정, 재발급 조건문
- Mypage.js -> 재발급에 대한 로직 적용 (현재 작성되어 있는 로직은 테스트 로직입니다!), 실제 적용되어 있는 로직 확인해보시면 될거같습니다
close #54
> [#54] 리프레쉬토큰으로 액세스토큰 발급 back서버 연동

- src/App.js
- src/containers/MonthBest.js
- src/containers/RestaurantList.js
- src/containers/TopReservation.js
- src/css/restaurantList.css
-  [사용자] 이달의맛집 카테고리 필터 구현
-   이달의 맛집 카테고리 기능 추가
-   식당 검색후 데이터 없을시 문구 추가
-   이달의 맛집,예약 탑 카테고리에 예약 데이터 없을시 문구 추가
-  AuthProvider 컴포넌트가 <Router> 바깥에서 사용되고있지만 Authcontext에서useNavigate사용중  
- useNavigate()는 React Router의 <Router> 컴포넌트 안에서만 사용가능.
- Router 안에 AuthProvider 감싸도록 코드수정
> [사용자] 이달의맛집 카테고리 필터 구현

- src/containers/Mypage.js
- src/context/AuthContext.js
내정보 조회 back 서버와 연동하였습니다.
추가 변경점
- AuthContext
- urlList 로직 get, post 등 method 매개변수로 받을 수 있도록 변경
```javascript
export const urlList = (method, path) => {
const host = 'http://localhost:8080';
return {
url: path,
method: method,
baseURL: host,
headers: {Authorization_Access: Cookies.get('accessToken'), Authorization_Refresh: Cookies.get('refreshToken')}
}
}
```
- 적용 예시
```javascript
axiosInstance(urlList("get", "/api/user"))
```
close #75
> [#75] 마이페이지 내정보 조회 back서버와 연동

- src/adminContainers/InquiriesAdmin.js
- src/adminContainers/ReservationAdmin.js
- src/adminContainers/ReviewsAdmin.js
- src/css/reservationManagement.css
- src/css/reviewsAdmin.css
- 리뷰
- 페이징과 리스트 겹치는 상태 해결
- 활성화 비활성화 상태값 반대로 나오는 상태 해결
- 데이터가 없을때 화면이 안나오는 상태 해결
- 예약
- 데이터가 없을때 화면이 안나오는 상태 해결
- 문의사항
- 데이터가 없을때 화면이 안나오는 상태 해결
> 관리자 리뷰관리,예약관리, 문의사항

- src/adminContainers/PlaceDetail.js
- src/adminContainers/PlaceEdit.js
- src/containers/InquiryFaq.js
- 관리자 음식점관리
- 음식점 수정 : 권한없는 유저로 등록하려할시  에러 메세지 띄우기
- 로그 지우기 에러로그 제외
- 메인페이지 문의
- 내 문의내역 버튼 비로그인자 접근불가 설정
> 관리자 음식점 관리, 메인페이지 문의

- src/containers/InquiryFaq.js
-  [사용자] 문의사항 자주 묻는 질문 추가 및 변경
close #79
> [사용자] 문의사항 자주 묻는 질문 추가 및 변경

- src/adminContainers/InquiriesAdmin.js
- src/adminContainers/InquiriesDetailAdmin.js
- src/adminContainers/MainAdmin.js
- src/adminContainers/MemberDetail.js
- src/adminContainers/MembersAdmin.js
- src/adminContainers/PlaceAdd.js
- src/adminContainers/PlaceDetail.js
- src/adminContainers/PlaceEdit.js
- src/adminContainers/PlacesAdmin.js
- src/adminContainers/ReservationAdmin.js
- src/adminContainers/ReviewsAdmin.js
> 회원관리, 음식점관리, 리뷰관리, 예약관리, 문의사항관리 리프레시토큰 추가

- .env
- src/App.js
- src/containers/Detail.js
- src/containers/ReservationDetail.js
- src/containers/ReservationList.js
- src/context/AuthContext.js
- 예약 기능 구현 : 예약 등록, 예약 수정, 예약 취소
- urlList () : 토큰정보만 있는 객체로 수정
> [#70] [사용자] 음식점 예약기능

- .env
> [#88] [삭제] .env

- .gitignore
- src/containers/Mypage.js
- src/containers/ReservationDetail.js
- src/context/AuthContext.js
- src/context/AxiosInstance.js
- 토큰 정보 담아서 header에 추가되게 변경
- urlList > 삭제
> [#90] [전역설정] AxiosInstance 수정

- src/containers/Main.js
- src/containers/MonthBest.js
- src/containers/RestaurantList.js
- src/containers/TopReservation.js
-  [사용자] 음식점 URL 호출 변경
- 메인,탑,이달,전체 페이지 URL 호출 변경
> [사용자] 음식점 URL 호출 변경

- package.json
- src/adminContainers/InquiriesAdmin.js
- src/containers/InquiryCreate.js
- src/containers/InquiryDetail.js
- src/containers/InquiryFaq.js
- src/containers/Main.js
- src/containers/MonthBest.js
- src/containers/MypageBookmark.js
- src/containers/MypageInquiry.js
- src/containers/MypageReviewlist.js
- src/containers/ReservationDetail.js
- src/containers/ReservationList.js
- src/containers/RestaurantList.js
- src/containers/ReviewComment.js
- src/containers/TopReservation.js
- src/context/AuthContext.js
- src/context/AxiosInstance.js
- isLogedIn 사라졌던거 다시 올림
- 백 호출URL변경으로 관리자 문의사항 주소호츨 재변경
> 마이페이지 호출주소 변경

- src/components/ReviewSlider.js
- src/containers/Main.js
-  [사용자] 메인 페이지 리뷰 슬라이드 수정
- 리뷰 슬라이드 수정
- 마지막 리뷰 다음 첫번째 리뷰가 붙게 변경
-  리뷰 작성자 이름 가운데 *표시 처리
-  리뷰 작성한 가게 이름 추가
> [사용자] 메인 페이지 리뷰 슬라이드 수정

- src/adminContainers/InquiriesAdmin.js
- src/adminContainers/InquiriesDetailAdmin.js
- src/adminContainers/MainAdmin.js
- src/adminContainers/MemberDetail.js
- src/adminContainers/MembersAdmin.js
- src/adminContainers/PlaceAdd.js
- src/adminContainers/PlaceDetail.js
- src/adminContainers/PlaceEdit.js
- src/adminContainers/ReservationAdmin.js
- src/adminContainers/ReviewsAdmin.js
- src/containers/Main.js
- src/css/home.css
- src/ownerContainers/ReservationOwner.js
ADMIN쪽 코드정리 + 메인화면 리뷰 디자인
- 코드정리 
- 메인 리뷰쪽 CSS추가
> ADMIN쪽 코드정리 + 메인화면 리뷰 디자인

- src/adminContainers/ReservationAdmin.js
- 예약 시간이 DB데이터와  9시간 차이나는  부분 수정
- 백코드수정으로 인한 호출 이름수정
> 관리자 예약 페이지 수정

- src/App.js
- src/adminContainers/MainAdmin.js
- src/components/Header.js
- src/containers/Main.js
- src/containers/MypageBookmark.js
- src/containers/MypageInquiry.js
- src/containers/ReservationList.js
- src/context/AuthContext.js
- src/ownerContainers/ReservationOwner.js
> [#107] [오너] 예약목록 페이지 및 sub 사용 제거

- src/App.js
- src/containers/FindPassword.js
- src/containers/MypageEdit.js
- src/containers/SignIn.js
- src/containers/SignUp.js
- src/css/findPassword.css
사용자 비밀번호 찾기 구현, back 서버와 연동
- 소셜로그인 사용자 비밀번호 찾기 불가능 -> 해당 플랫폼 이용 메세지 출력
- 비밀번호 찾기 이벤트 -> 이름, 생년월일, 휴대폰번호 입력
- 비밀번호 찾기 성공 시 랜덤 비밀번호 12자리 발급 -> 비밀번호 변경 유도 문구 추가 -> 로그인 화면 리다이렉트
close #114
> 사용자 비밀번호 찾기 구현, back서버와 연동

- src/containers/MypageInquiry.js
- src/containers/MypageReviewEdit.js
- src/containers/MypageReviewlist.js
- 마이 리뷰
- sub삭제
- 리뷰 수정시 수정되었습니다 알림 + 목록으로 이동
- 문의사항
- sub삭제
> [마이페이지] 유저  이메일 유지 변경

- src/adminContainers/ReviewsAdmin.js
back서버 앤드포인트 변경에 따른 front서버 요청 앤드포인트 변경
close #122
> [#122] 관리자 리뷰 요청 앤드포인트 변경

- src/adminContainers/ReservationAdmin.js
back서버 리팩토링에 따른 front 요청 앤드포인트 변경하였습니다.
close #124
> [#124] 관리자 리뷰 요청 앤드포인트 변경

- src/containers/InquiryDetail.js
- src/containers/SignUp.js
- src/css/inquiry.css
- 사용자 문의 내역에 관리자가 답변 등록시 해당 답변도 같이 노출
> [#128] [문의사항] 사용자 문의 내역 - 관리자 답변 추가

- src/App.js
- src/adminContainers/MemberDetail.js
- src/adminContainers/MembersAdmin.js
- src/adminContainers/NavBarAdmin.js
- src/components/NavBarAdmin.js
- src/containers/Detail.js
- src/containers/InquiryCreate.js
- src/containers/InquiryDetail.js
- src/containers/MypageBookmark.js
- src/containers/MypageInquiry.js
- src/containers/MypageReviewEdit.js
- src/containers/MypageReviewlist.js
- src/containers/ReservationDetail.js
- src/containers/ReservationList.js
- src/containers/ReviewComment.js
> user 앤드포인트 변경

- src/ownerContainers/ReservationOwner.js
- 기존 admin 예약 취소로직으로 동작 -> 별도 owner 로직 생성
> [#133] [오너] 예약 로직 수정 - ownerService로직 으로 수정
